// `.open-next/worker.js` is generated by the Cloudflare build.
// @ts-expect-error The module does not exist until `opennextjs-cloudflare build` runs.
import openNextWorker from "./.open-next/worker.js";

const MODEL_PROXY_PREFIX = "/api/local-ai/models/";
const APPROVED_MODEL_IDS = new Set([
  "SmolLM2-360M-Instruct-q4f32_1-MLC",
  "Llama-3.2-1B-Instruct-q4f16_1-MLC",
]);
const SAFE_FILE_SEGMENT = /^[A-Za-z0-9._-]+$/;
const FORWARDED_REQUEST_HEADERS = ["if-modified-since", "if-none-match", "range"];
const FORWARDED_RESPONSE_HEADERS = [
  "accept-ranges",
  "cache-control",
  "content-length",
  "content-range",
  "content-type",
  "etag",
  "last-modified",
];

type WorkerContext = {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
};

function decodePathSegment(value: string) {
  try {
    return decodeURIComponent(value);
  } catch {
    return null;
  }
}

async function proxyModelFile(request: Request) {
  if (request.method !== "GET" && request.method !== "HEAD") {
    return new Response("Method not allowed.", { status: 405, headers: { Allow: "GET, HEAD" } });
  }

  const pathname = new URL(request.url).pathname;
  const segments = pathname.slice(MODEL_PROXY_PREFIX.length).split("/").map(decodePathSegment);
  const [modelId, resolveSegment, mainSegment, ...file] = segments;
  if (
    !modelId ||
    !APPROVED_MODEL_IDS.has(modelId) ||
    resolveSegment !== "resolve" ||
    mainSegment !== "main" ||
    !file.length ||
    file.some((segment) => !segment || !SAFE_FILE_SEGMENT.test(segment))
  ) {
    return new Response("Model file not found.", { status: 404 });
  }

  const upstreamUrl = new URL(
    `${encodeURIComponent(modelId)}/resolve/main/${file.map((segment) => encodeURIComponent(segment!)).join("/")}`,
    "https://huggingface.co/mlc-ai/",
  );

  const filename = file.at(-1);
  if (filename !== "mlc-chat-config.json" && filename !== "tensor-cache.json") {
    // Cloudflare's fetch connection to Hugging Face's Xet bridge can close a
    // successful large response early. Redirect weight/tokenizer downloads to
    // the model host instead; Hugging Face supplies CORS headers for these
    // public files, and WebLLM still caches the completed response locally.
    return new Response(null, {
      status: 307,
      headers: {
        "Cache-Control": "no-store",
        Location: upstreamUrl.href,
        "X-Content-Type-Options": "nosniff",
      },
    });
  }

  const upstreamHeaders = new Headers();
  for (const name of FORWARDED_REQUEST_HEADERS) {
    const value = request.headers.get(name);
    if (value) upstreamHeaders.set(name, value);
  }

  let upstream: Response;
  try {
    upstream = await fetch(upstreamUrl, {
      method: request.method,
      headers: upstreamHeaders,
      redirect: "follow",
      signal: request.signal,
    });
  } catch {
    return new Response("The model host is temporarily unavailable.", {
      status: 502,
      headers: { "Cache-Control": "no-store" },
    });
  }

  const responseHeaders = new Headers();
  for (const name of FORWARDED_RESPONSE_HEADERS) {
    const value = upstream.headers.get(name);
    if (value) responseHeaders.set(name, value);
  }
  responseHeaders.set("X-Content-Type-Options", "nosniff");

  // Bypass Next/OpenNext's Node response conversion for multi-hundred-MB model
  // shards. Passing the native fetch body through keeps the stream attached to
  // the Cloudflare request for its full lifetime without buffering it in memory.
  return new Response(upstream.body, {
    status: upstream.status,
    statusText: upstream.statusText,
    headers: responseHeaders,
  });
}

const worker = {
  async fetch(request: Request, env: unknown, ctx: WorkerContext) {
    if (new URL(request.url).pathname.startsWith(MODEL_PROXY_PREFIX)) {
      return proxyModelFile(request);
    }
    return openNextWorker.fetch(request, env, ctx);
  },
};

export default worker;

// Required when OpenNext's optional durable-object caches are enabled.
// @ts-expect-error The module does not exist until `opennextjs-cloudflare build` runs.
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
