// `.open-next/worker.js` is generated by the Cloudflare build.
// @ts-expect-error The module does not exist until `opennextjs-cloudflare build` runs.
import openNextWorker from "./.open-next/worker.js";
import { DurableObject } from "cloudflare:workers";
import { handleExportMetric, type ExportMetricsEnv } from "./lib/export-metrics-server";
import { handleInlineAIMetric, type InlineAIMetricsEnv } from "./lib/inline-ai-metrics-server";
import {
  handleJobApplicationMetric,
  type JobApplicationMetricsEnv,
} from "./lib/job-application-metrics-server";
import { LOCAL_AI_MODELS } from "./lib/local-ai-models";
import {
  handleWebRTCHandoffSignaling,
  WEBRTC_HANDOFF_SIGNALING_PATH,
  type WebRTCHandoffRoomRecord,
} from "./lib/webrtc-handoff-signaling-server";
import {
  handleWebRTCTurnCredentials,
  WEBRTC_TURN_CREDENTIALS_PATH,
  type WebRTCTurnEnv,
} from "./lib/webrtc-turn-server";

const MODEL_PROXY_PREFIX = "/api/local-ai/models/";
const MODEL_CACHE_PATH_VERSIONS = new Set(["webllm-cache-v2", "webllm-cache-v2-qwen3"]);
const APPROVED_MODEL_IDS = new Set<string>(LOCAL_AI_MODELS.map((model) => model.id));
const SAFE_FILE_SEGMENT = /^[A-Za-z0-9._-]+$/;
const FORWARDED_REQUEST_HEADERS = ["if-modified-since", "if-none-match", "range"];
const FORWARDED_RESPONSE_HEADERS = [
  "accept-ranges",
  "cache-control",
  "content-length",
  "content-range",
  "content-type",
  "etag",
  "last-modified",
];

type WorkerContext = {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
};

type HandoffRoomNamespace = {
  getByName(name: string): { fetch(request: Request): Promise<Response> };
};

type HandoffRoomStorage = {
  get<T>(key: string): Promise<T | undefined>;
  put<T>(key: string, value: T): Promise<void>;
  deleteAll(): Promise<void>;
  setAlarm(scheduledTime: number | Date): Promise<void>;
};

type HandoffRoomState = { storage: HandoffRoomStorage };

type WorkerEnv = ExportMetricsEnv &
  InlineAIMetricsEnv &
  JobApplicationMetricsEnv &
  WebRTCTurnEnv & { HANDOFF_ROOMS?: HandoffRoomNamespace };

export class WebRTCHandoffRoom extends DurableObject<WorkerEnv> {
  private readonly roomState: HandoffRoomState;

  constructor(state: HandoffRoomState, env: WorkerEnv) {
    super(state, env);
    this.roomState = state;
  }

  fetch(request: Request) {
    const roomId = new URL(request.url).pathname.slice(WEBRTC_HANDOFF_SIGNALING_PATH.length);
    return handleWebRTCHandoffSignaling(request, roomId, {
      read: () => this.roomState.storage.get<WebRTCHandoffRoomRecord>("room"),
      write: (record) => this.roomState.storage.put("room", record),
      delete: () => this.roomState.storage.deleteAll(),
      scheduleExpiry: (expiresAt) => this.roomState.storage.setAlarm(expiresAt),
    });
  }

  alarm() {
    return this.roomState.storage.deleteAll();
  }
}

function decodePathSegment(value: string) {
  try {
    return decodeURIComponent(value);
  } catch {
    return null;
  }
}

async function proxyModelFile(request: Request) {
  if (request.method !== "GET" && request.method !== "HEAD") {
    return new Response("Method not allowed.", { status: 405, headers: { Allow: "GET, HEAD" } });
  }

  const pathname = new URL(request.url).pathname;
  const segments = pathname.slice(MODEL_PROXY_PREFIX.length).split("/").map(decodePathSegment);
  const [modelId, resolveSegment, mainSegment, ...requestedFile] = segments;
  const file = MODEL_CACHE_PATH_VERSIONS.has(requestedFile[0] ?? "")
    ? requestedFile.slice(1)
    : requestedFile;
  if (
    !modelId ||
    !APPROVED_MODEL_IDS.has(modelId) ||
    resolveSegment !== "resolve" ||
    mainSegment !== "main" ||
    !file.length ||
    file.some((segment) => !segment || !SAFE_FILE_SEGMENT.test(segment))
  ) {
    return new Response("Model file not found.", {
      status: 404,
      headers: { "Cache-Control": "no-store" },
    });
  }

  const upstreamUrl = new URL(
    `${encodeURIComponent(modelId)}/resolve/main/${file.map((segment) => encodeURIComponent(segment!)).join("/")}`,
    "https://huggingface.co/mlc-ai/",
  );

  const upstreamHeaders = new Headers();
  for (const name of FORWARDED_REQUEST_HEADERS) {
    const value = request.headers.get(name);
    if (value) upstreamHeaders.set(name, value);
  }

  const filename = file.at(-1);
  if (filename?.endsWith(".bin")) {
    // Cloudflare's connection to Hugging Face's Xet bridge can close a large
    // streamed response early. Resolve the short Hugging Face pointer inside
    // the Worker, then send the browser directly to Xet, whose signed response
    // has working CORS for the app origin.
    try {
      const pointer = await fetch(upstreamUrl, {
        method: "HEAD",
        redirect: "manual",
        signal: request.signal,
      });
      const location = pointer.headers.get("location");
      if (!location) throw new Error("The model host did not provide a download URL.");
      return new Response(null, {
        status: 307,
        headers: {
          "Cache-Control": "no-store",
          Location: new URL(location, upstreamUrl).href,
          "X-Content-Type-Options": "nosniff",
        },
      });
    } catch {
      return new Response("The model host is temporarily unavailable.", {
        status: 502,
        headers: { "Cache-Control": "no-store" },
      });
    }
  }

  let upstream: Response;
  try {
    upstream = await fetch(upstreamUrl, {
      method: request.method,
      headers: upstreamHeaders,
      redirect: "follow",
      signal: request.signal,
    });
  } catch {
    return new Response("The model host is temporarily unavailable.", {
      status: 502,
      headers: { "Cache-Control": "no-store" },
    });
  }

  const responseHeaders = new Headers();
  for (const name of FORWARDED_RESPONSE_HEADERS) {
    const value = upstream.headers.get(name);
    if (value) responseHeaders.set(name, value);
  }
  responseHeaders.set("X-Content-Type-Options", "nosniff");

  // Tokenizers and manifests are small enough to buffer. Doing so detaches the
  // browser response from Cloudflare's upstream stream, which can otherwise
  // end early even though the upstream status is 200.
  const body = request.method === "HEAD" ? null : await upstream.arrayBuffer();
  if (body) responseHeaders.set("Content-Length", String(body.byteLength));
  return new Response(body, {
    status: upstream.status,
    statusText: upstream.statusText,
    headers: responseHeaders,
  });
}

const worker = {
  async fetch(request: Request, env: WorkerEnv, ctx: WorkerContext) {
    const pathname = new URL(request.url).pathname;
    if (pathname.startsWith(WEBRTC_TURN_CREDENTIALS_PATH)) {
      const roomId = pathname.slice(WEBRTC_TURN_CREDENTIALS_PATH.length);
      if (request.method !== "OPTIONS") {
        if (!env.HANDOFF_ROOMS) {
          return new Response("Device handoff is unavailable.", {
            status: 503,
            headers: { "Cache-Control": "no-store" },
          });
        }
        const roomUrl = new URL(`${WEBRTC_HANDOFF_SIGNALING_PATH}${roomId}`, request.url);
        roomUrl.searchParams.set("role", "receiver");
        const roomRequest = new Request(roomUrl, {
          method: "GET",
          headers: request.headers.get("origin")
            ? { Origin: request.headers.get("origin")! }
            : undefined,
        });
        const roomResponse = await env.HANDOFF_ROOMS.getByName(roomId).fetch(roomRequest);
        if (roomResponse.status !== 200) {
          return new Response("Active handoff room not found.", {
            status: 404,
            headers: { "Cache-Control": "no-store" },
          });
        }
      }
      return handleWebRTCTurnCredentials(request, roomId, env);
    }
    if (pathname.startsWith(WEBRTC_HANDOFF_SIGNALING_PATH)) {
      const roomId = pathname.slice(WEBRTC_HANDOFF_SIGNALING_PATH.length);
      if (!env.HANDOFF_ROOMS) {
        return new Response("Device handoff is unavailable.", {
          status: 503,
          headers: { "Cache-Control": "no-store" },
        });
      }
      return env.HANDOFF_ROOMS.getByName(roomId).fetch(request);
    }
    const metricResponse = await handleExportMetric(request, env);
    if (metricResponse) return metricResponse;
    const inlineAIMetricResponse = await handleInlineAIMetric(request, env);
    if (inlineAIMetricResponse) return inlineAIMetricResponse;
    const jobApplicationMetricResponse = await handleJobApplicationMetric(request, env);
    if (jobApplicationMetricResponse) return jobApplicationMetricResponse;
    if (pathname.startsWith(MODEL_PROXY_PREFIX)) {
      return proxyModelFile(request);
    }
    return openNextWorker.fetch(request, env, ctx);
  },
};

export default worker;

// Required when OpenNext's optional durable-object caches are enabled.
// @ts-expect-error The module does not exist until `opennextjs-cloudflare build` runs.
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
