// `.open-next/worker.js` is generated by the Cloudflare build.
// @ts-expect-error The module does not exist until `opennextjs-cloudflare build` runs.
import openNextWorker from "./.open-next/worker.js";
import { LOCAL_AI_MODELS } from "./lib/local-ai-models";

const MODEL_PROXY_PREFIX = "/api/local-ai/models/";
const MODEL_CACHE_PATH_VERSION = "webllm-cache-v2";
const APPROVED_MODEL_IDS = new Set<string>(LOCAL_AI_MODELS.map((model) => model.id));
const SAFE_FILE_SEGMENT = /^[A-Za-z0-9._-]+$/;
const FORWARDED_REQUEST_HEADERS = ["if-modified-since", "if-none-match", "range"];
const FORWARDED_RESPONSE_HEADERS = [
  "accept-ranges",
  "cache-control",
  "content-length",
  "content-range",
  "content-type",
  "etag",
  "last-modified",
];

type WorkerContext = {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
};

function decodePathSegment(value: string) {
  try {
    return decodeURIComponent(value);
  } catch {
    return null;
  }
}

async function proxyModelFile(request: Request) {
  if (request.method !== "GET" && request.method !== "HEAD") {
    return new Response("Method not allowed.", { status: 405, headers: { Allow: "GET, HEAD" } });
  }

  const pathname = new URL(request.url).pathname;
  const segments = pathname.slice(MODEL_PROXY_PREFIX.length).split("/").map(decodePathSegment);
  const [modelId, resolveSegment, mainSegment, ...requestedFile] = segments;
  const file = requestedFile[0] === MODEL_CACHE_PATH_VERSION ? requestedFile.slice(1) : requestedFile;
  if (
    !modelId ||
    !APPROVED_MODEL_IDS.has(modelId) ||
    resolveSegment !== "resolve" ||
    mainSegment !== "main" ||
    !file.length ||
    file.some((segment) => !segment || !SAFE_FILE_SEGMENT.test(segment))
  ) {
    return new Response("Model file not found.", { status: 404 });
  }

  const upstreamUrl = new URL(
    `${encodeURIComponent(modelId)}/resolve/main/${file.map((segment) => encodeURIComponent(segment!)).join("/")}`,
    "https://huggingface.co/mlc-ai/",
  );

  const upstreamHeaders = new Headers();
  for (const name of FORWARDED_REQUEST_HEADERS) {
    const value = request.headers.get(name);
    if (value) upstreamHeaders.set(name, value);
  }

  const filename = file.at(-1);
  if (filename?.endsWith(".bin")) {
    // Cloudflare's connection to Hugging Face's Xet bridge can close a large
    // streamed response early. Resolve the short Hugging Face pointer inside
    // the Worker, then send the browser directly to Xet, whose signed response
    // has working CORS for the app origin.
    try {
      const pointer = await fetch(upstreamUrl, {
        method: "HEAD",
        redirect: "manual",
        signal: request.signal,
      });
      const location = pointer.headers.get("location");
      if (!location) throw new Error("The model host did not provide a download URL.");
      return new Response(null, {
        status: 307,
        headers: {
          "Cache-Control": "no-store",
          Location: new URL(location, upstreamUrl).href,
          "X-Content-Type-Options": "nosniff",
        },
      });
    } catch {
      return new Response("The model host is temporarily unavailable.", {
        status: 502,
        headers: { "Cache-Control": "no-store" },
      });
    }
  }

  let upstream: Response;
  try {
    upstream = await fetch(upstreamUrl, {
      method: request.method,
      headers: upstreamHeaders,
      redirect: "follow",
      signal: request.signal,
    });
  } catch {
    return new Response("The model host is temporarily unavailable.", {
      status: 502,
      headers: { "Cache-Control": "no-store" },
    });
  }

  const responseHeaders = new Headers();
  for (const name of FORWARDED_RESPONSE_HEADERS) {
    const value = upstream.headers.get(name);
    if (value) responseHeaders.set(name, value);
  }
  responseHeaders.set("X-Content-Type-Options", "nosniff");

  // Tokenizers and manifests are small enough to buffer. Doing so detaches the
  // browser response from Cloudflare's upstream stream, which can otherwise
  // end early even though the upstream status is 200.
  const body = request.method === "HEAD" ? null : await upstream.arrayBuffer();
  if (body) responseHeaders.set("Content-Length", String(body.byteLength));
  return new Response(body, {
    status: upstream.status,
    statusText: upstream.statusText,
    headers: responseHeaders,
  });
}

const worker = {
  async fetch(request: Request, env: unknown, ctx: WorkerContext) {
    if (new URL(request.url).pathname.startsWith(MODEL_PROXY_PREFIX)) {
      return proxyModelFile(request);
    }
    return openNextWorker.fetch(request, env, ctx);
  },
};

export default worker;

// Required when OpenNext's optional durable-object caches are enabled.
// @ts-expect-error The module does not exist until `opennextjs-cloudflare build` runs.
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
